<?php 

/**
 * @package delakanda/mazzuma
 * @author  Delali Kanda <delakanda@gmail.com>
 * @license MIT
 **/

namespace Delakanda\Mazzuma\Api\Transactions;

use Delakanda\Mazzuma\Api\ApiBase;
use Delakanda\Mazzuma\Traits\Assignable;

/**
 * This class Manages Mazzuma mobile money operations
 **/

class MobileMoney extends ApiBase
{
  use Assignable;

  /**
   * The amount to be paid
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $price;

  /**
   * This is the network of the mobile money account that would be making the payment (your customer).
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $network;

  /**
   * This is the mobile money account the payments shall end up in. (your account).
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $recipient_number;

  /**
   * This is the mobile money account that would be making the payment (your customers).
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $sender;

  /**
   * This denotes the direction of cash flow. For example, rmta can be understood as an acronym of the phrase ‘receive mtn to airtel’, 
   * which means you would be receiving money to your Airtel account (the recipient number) from an MTN number(the sender). 
   * This format would hold for all transaction requests sent to the API. Do not forget to append the r at beginning.
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $option;

  /**
   * This optional parameter can be added to track the status of a transaction after it has been completed by use of our check status endpoint. 
   * Please note that the order ID is not the same as the transaction ID returned after a transaction request.
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $orderID;

  /**
   * This is the token generated by Vodafone users in order to complete mobile money payments. 
   * This parameter is only required when the payment is to be made by a Vodafone user.
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $token;

  private $requiredParams = [
    'price',
    'network',
    'recipient_number',
    'sender',
    'option'
  ];

  public function __construct($data=[])
  {
    $this->assignToMembers($data, $this->requiredParams);
  }

  public function initiatePayment()
  {
    $paymentData = [
      'price' =>  $this->price->value,
      'network' => $this->network->value,
      'recipient_number' => $this->recipient_number->value,
      'sender' => $this->sender->value,
      'option' => $this->option->value,
      'option' => $this->option->value,
      'apiKey' => $this->config->getApiKey(),
      'orderID' => $this->orderID ? $this->orderID->value : null,
      'token' => $this->token->value
    ];

    dD($paymentData);
  }
}