<?php 

/**
 * @package delakanda/mazzuma
 * @author  Delali Kanda <delakanda@gmail.com>
 * @license MIT
 **/

namespace Delakanda\Mazzuma\Api\Transactions;

use Delakanda\Mazzuma\Api\ApiBase;
use Delakanda\Mazzuma\Traits\Validatable;
use Delakanda\Mazzuma\Traits\Assignable;
use Delakanda\Mazzuma\Utils\Parameter;

/**
 * This class Manages Mazzuma mobile money operations
 **/

class MobileMoney extends ApiBase
{
  use Assignable;
  use Validatable;

  /**
   * The amount to be paid
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $price;

  /**
   * This is the network of the mobile money account that would be making the payment (your customer).
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $network;

  /**
   * This is the mobile money account the payments shall end up in. (your account).
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $recipient_number;

  /**
   * This is the mobile money account that would be making the payment (your customers).
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $sender;

  /**
   * This denotes the direction of cash flow. For example, rmta can be understood as an acronym of the phrase ‘receive mtn to airtel’, 
   * which means you would be receiving money to your Airtel account (the recipient number) from an MTN number(the sender). 
   * This format would hold for all transaction requests sent to the API. Do not forget to append the r at beginning.
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $option;

  /**
   * This optional parameter can be added to track the status of a transaction after it has been completed by use of our check status endpoint. 
   * Please note that the order ID is not the same as the transaction ID returned after a transaction request.
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $orderID;

  /**
   * This is the token generated by Vodafone users in order to complete mobile money payments. 
   * This parameter is only required when the payment is to be made by a Vodafone user.
   * @var \Delakanda\Mazzuma\Utils\Parameter
   **/
  protected $token;

  private $requiredParams = [
    "price","network","recipient_number","sender","option"
  ];

  private $optionalParams = [
    "orderID","token"
  ];

  public function __construct()
  {
    parent::__construct();
    $this->setMemberVariables(array_merge($this->requiredParams, $this->optionalParams), $this->requiredParams);
  }

  /**
   * Initiate mobile money transaction
   * @return string JSON with an http status code
   **/
  public function initiateTransaction()
  {
    $this->validateParameters();

    $paymentData = [
      'price' =>  $this->price->value,
      'network' => $this->network->value,
      'recipient_number' => $this->recipient_number->value,
      'sender' => $this->sender->value,
      'option' => $this->option->value,
      'option' => $this->option->value,
      'apiKey' => $this->config->getApiKey(),
      'orderID' => $this->orderID ? $this->orderID->value : null,
      'token' => $this->token ? $this->token->value : null
    ];

    // $uri = "api_call.php";
    $uri = "mazzumatest";

    $response = $this->postRequest($uri, $paymentData);
    return $response;
  }

  /**
   * Check mobile money transaction status with orderID set
   * @return string JSON with an http status code
   **/
  public function checkTransactionStatus()
  {
    if(!$this->orderID)
    {
      return $this->customResponse([
        'status' =>  0,
        'message' => 'orderId is not set on this instance'
      ], 400);
    }

    $uri = "mazzumatestget?orderID={$this->orderID->value}";
    $response = $this->getRequest($uri);
    return $response;
  }

  public function price(float $amount)
  {
    $this->price = new Parameter($amount, true);
    return $this;
  }
  
  public function network(string $network)
  {
    $this->network = new Parameter($network, true);
    return $this;
  }

  public function recipientNumber(string $recipient_number)
  {
    $this->recipient_number = new Parameter($recipient_number, true);
    return $this;
  }

  public function sender(string $sender)
  {
    $this->sender = new Parameter($sender, true);
    return $this;
  }

  public function option(string $option)
  {
    $this->option = new Parameter($option, true);
    return $this;
  }

  public function orderId(string $orderId)
  {
    $this->orderID = new Parameter($orderId, false);
    return $this;
  }

  public function token(string $token)
  {
    $this->token = new Parameter($token, false);
    return $this;
  }
}